---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - enterprise.mftest.com
  resources:
  - widgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.mftest.com
  resources:
  - widgets/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.mftest.com
  resources:
  - widgets/status
  verbs:
  - get
  - patch
  - update
