# permissions for end users to edit widgets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: widget-editor-role
rules:
- apiGroups:
  - enterprise.mftest.com
  resources:
  - widgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.mftest.com
  resources:
  - widgets/status
  verbs:
  - get
