apiVersion: enterprise.mftest.com/v1alpha1
kind: Widget
metadata:
  labels:
    app.kubernetes.io/name: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: widget-sample
spec:
  # TODO(user): Add fields here
